// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {gui} from '../models';

export function DiscoverDevices():Promise<Array<gui.DeviceResult>>;

export function GetConfig():Promise<gui.ConfigResult>;

export function Install(arg1:string,arg2:string):Promise<gui.InstallResult>;

export function LoadConfig(arg1:string):Promise<gui.ConfigResult>;
