// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DiscoverDevices() {
  return window['go']['gui']['App']['DiscoverDevices']();
}

export function GetConfig() {
  return window['go']['gui']['App']['GetConfig']();
}

export function Install(arg1, arg2) {
  return window['go']['gui']['App']['Install'](arg1, arg2);
}

export function LoadConfig(arg1) {
  return window['go']['gui']['App']['LoadConfig'](arg1);
}
